//Add new product types
export const ADD_PRODUCT_NAME = "ADD_PRODUCT_NAME";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const ADD_PRODUCT_PRICE = "ADD_PRODUCT_PRICE";
export const ADD_PRODUCT_QUANTITY = "ADD_PRODUCT_QUANTITY";
export const ADD_PRODUCT_GENDER = "ADD_PRODUCT_GENDER";
export const ADD_PRODUCT_IMAGES = "ADD_PRODUCT_IMAGES";
export const ADD_PRODUCT_IMAGE_PATHS = "ADD_PRODUCT_IMAGE_PATHS";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";
export const CLEAR_PRODUCT_ERRORS = "CLEAR_PRODUCT_ERRORS";

//Sign Up types
export const ADD_SIGNUP_NAME = "ADD_SIGNUP_NAME";
export const ADD_SIGNUP_SURNAME = "ADD_SIGNUP_SURNAME";
export const ADD_SIGNUP_AGE = "ADD_SIGNUP_AGE";
export const ADD_SIGNUP_EMAIL = "ADD_SIGNUP_EMAIL";
export const ADD_SIGNUP_PASSWORD = "ADD_SIGNUP_PASSWORD";
export const ADD_SIGNUP_CONFIRM_PASSWORM = "ADD_SIGNUP_CONFIRM_PASSWORM";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP = "SIGNUP";

//Login
export const ADD_LOGIN_EMAIL = "ADD_LOGIN_EMAIL";
export const ADD_LOGIN_PASSWORD = "ADD_LOGIN_PASSWORD";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

//Homepage
export const GET_TOP_PRODUCTS = "GET_TOP_PRODUCTS";
export const GET_TOP_PRODUCTS_FAILED = "GET_TOP_PRODUCTS_FAILED";

//Get Product page

export const GET_PRODUCT = "GET_PRODUCT";
