//Add new product types
export const ADD_PRODUCT_IMAGES = "ADD_PRODUCT_IMAGES";
export const ADD_PRODUCT_IMAGE_PATHS = "ADD_PRODUCT_IMAGE_PATHS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

//User constants
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";
export const LOG_IN = "LOG_IN";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_OUT = "LOG_OUT";
export const LOG_OUT_FAILED = "LOG_OUT_FAILED";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Homepage
export const GET_TOP_PRODUCTS = "GET_TOP_PRODUCTS";
export const GET_TOP_PRODUCTS_FAILED = "GET_TOP_PRODUCTS_FAILED";

//Product constants
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT_TO_SHOPPING_CART = "ADD_PRODUCT_TO_SHOPPING_CART";
export const ADD_PRODUCT_TO_SHOPPING_CART_FAILED =
  "ADD_PRODUCT_TO_SHOPPING_CART_FAILED";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID_FAILED = "DELETE_PRODUCT_BY_ID_FAILED";

//Search products
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const CLEAR_SEARCHING_RESULTS = "CLEAR_SEARCHING_RESULTS";

//category constants
export const GET__ALL_CATEGORIES = "GET__ALL_CATEGORIES";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const ADD_NEW_CATEGORY_FAILED = "ADD_NEW_CATEGORY_FAILED";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";

//Change product properties
export const CHANGE_PRODUCT_NAME = "CHANGE_PRODUCT_NAME";
export const CHANGE_PRODUCT_CATEGORY = "CHANGE_PRODUCT_CATEGORY";
export const CHANGE_PRODUCT_PRICE = "CHANGE_PRODUCT_PRICE";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
