//Add new product types
export const ADD_PRODUCT_NAME = 'ADD_PRODUCT_NAME';
export const ADD_PRODUCT_CATEGORY = 'ADD_PRODUCT_CATEGORY';
export const ADD_PRODUCT_PRICE = 'ADD_PRODUCT_PRICE';
export const ADD_PRODUCT_QUANTITY = 'ADD_PRODUCT_QUANTITY';
export const ADD_PRODUCT_GENDER = 'ADD_PRODUCT_GENDER';
export const ADD_PRODUCT_IMAGES = 'ADD_PRODUCT_IMAGES';
export const ADD_PRODUCT_IMAGE_PATHS = 'ADD_PRODUCT_IMAGE_PATHS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const CLEAR_PRODUCT_ERRORS = 'CLEAR_PRODUCT_ERRORS';

//User types
export const ADD_SIGNUP_NAME = 'ADD_SIGNUP_NAME';
export const ADD_SIGNUP_SURNAME = 'ADD_SIGNUP_SURNAME';
export const ADD_SIGNUP_AGE = 'ADD_SIGNUP_AGE';
export const ADD_SIGNUP_EMAIL = 'ADD_SIGNUP_EMAIL';
export const ADD_SIGNUP_PASSWORD = 'ADD_SIGNUP_PASSWORD';
export const ADD_SIGNUP_CONFIRM_PASSWORM = 'ADD_SIGNUP_CONFIRM_PASSWORM';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';
export const SIGNUP = 'SIGNUP';
